global:
  scrape_interval: 10s
  evaluation_interval: 20s
  rule_files:
    - alert.rules

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['endereco_IP_maquina6:9090']

  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['endereco_IP_maquina:9187']
